modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"


[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL="https://github.com/EDGtheXu/BetterExperience/" #optional
logoFile= "logo.png" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''


[[mixins]]
config = "${mod_id}.mixins.json"


[[accessTransformers]]
file="META-INF/accesstransformer.cfg"


[[dependencies."${mod_id}"]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId = "confluence"
type = "optional"
versionRange = "[1.1.4,)"
ordering = "NONE"
side = "BOTH"

