# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package
permissions: write-all

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: "gradle"

      - name: Add permissions for gradlew
        run: chmod +x gradlew

      - name: Generate assets
        run: ./gradlew runData

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: v1.0.0-neo
          prerelease: true
          title: "Better Experience Test Build"
          files: ./build/libs/*.jar
          modrinth-name: Better Experience